export const loaderData = [
    {
        name: "babel-loader",
        content: '在import或加载模块时，对es6代码进行预处理，es6语法转化为es5语法'
    },
    {name: "yaml-frontmatter-loader" },
    {name: "cache-loader" },
    {name: "coffee-loader" },
    {name: "coffee-redux-loader" },
    {name: "coverjs-loader" },
    {name: "css-loader" },
    {name: "exports-loader" },
    {name: "expose-loader" },
    {name: "extract-loader" },
    {name: "file-loader" },
    {name: "gzip-loader" },
    {name: "html-loader" },
    {name: "i18n-loader" },
    {name: "imports-loader" },
    {name: "istanbul-instrumenter-loader" },
    {name: "jshint-loader" },
    {name: "json-loader" },
    {name: "json5-loader" },
    {name: "less-loader" },
    {name: "bundle-loader" },
    {name: "multi-loader" },
    {name: "node-loader" },
    {name: "null-loader" },
    {name: "polymer-webpack-loader" },
    {name: "postcss-loader" },
    {name: "raw-loader" },
    {name: "react-proxy-loader" },
    {name: "restyle-loader" },
    {name: "sass-loader" },
    {name: "script-loader" },
    {name: "source-map-loader" },
    {name: "style-loader" },
    {name: "svg-inline-loader" },
    {name: "thread-loader" },
    {name: "transform-loader" },
    {name: "url-loader" },
    {name: "val-loader" },
    {name: "worker-loader" },
    {name: "mocha-loader" }
];
